Repository nx-go/nx-go, pull requests merged in 2024-11, with the labels that each got.

#141 chore: stick pnpm version to v8
  .github/actions/setup/action.yml
  .gitignore
  .prettierignore
  package.json
Labels: dependencies

#94 support tinygo
  docs/executors/build.md
  packages/nx-go/src/executors/build/executor.spec.ts
  packages/nx-go/src/executors/build/executor.ts
  packages/nx-go/src/executors/build/schema.d.ts
  packages/nx-go/src/executors/build/schema.json
Labels: type: feature

#142 Add support of Nx 20
  .github/workflows/ci.yml
  .github/workflows/release.yml
  README.md
  packages/nx-go/package.json
Labels: type: feature, dependencies

#143 Add an option to use the plugin without Go installed
  README.md
  docs/options.md
  packages/nx-go/src/graph/create-dependencies.spec.ts
  packages/nx-go/src/graph/create-dependencies.ts
  packages/nx-go/src/type.d.ts
  packages/nx-go/src/utils/go-bridge.spec.ts
  packages/nx-go/src/utils/go-bridge.ts
Labels: type: feature
